package openai

import (
	"fmt"

	"github.com/flipped-aurora/gin-vue-admin/server/model/openai"
)

type ServiceGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	OpenaiService
	TelegramService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}

//接受telegram服务器传过来的命令命令,处理命令
func (telegramService *TelegramService) CommonDo(command string, telegramBotUpdate openai.TelegramBotUpdate, args ...string) {
	var sendMessageInfo openai.SendMessageToUserStruct
	// var wallpaper wallpaper.Wallpaper
	// var sendPhoto openai.SendPhotoS
	// client := resty.New()
	//随机返回一张美女壁纸
	if command == "/ask" {
		fmt.Println(telegramBotUpdate.Message.Text)
		sendMessageInfo.ChatId = telegramBotUpdate.Message.Chat.Id
		sendMessageInfo.Text = "回复了哟"
		sendMessageInfo.ParseMode = "HTML"
		telegramService.SendMessage(sendMessageInfo)
	}

	//帮助信息
	if command == "/help" {
		// var count int64 = 100
		// db := global.GVA_DB.Model(&wallpaper)
		// db.Count(&count)
		tempStr := `欢迎使用神医的oeoChat机器人,此机器人对接openAi官方API。
		使用方法:直接发送文字问题,免费额度有限，请珍惜使用.
		按文字生成图片的功能正在开发中
`
		sendMessageInfo.ChatId = telegramBotUpdate.Message.Chat.Id
		// sendMessageInfo.Text = fmt.Sprintf(tempStr)
		sendMessageInfo.Text = tempStr
		sendMessageInfo.ParseMode = "HTML"
		telegramService.SendMessage(sendMessageInfo)
	}
	//帮助信息
	if command == "/start" {
		sendMessageInfo.ChatId = telegramBotUpdate.Message.Chat.Id
		sendMessageInfo.Text = `欢迎使用神医的oeoChat机器人,此机器人对接openAi官方API。
		使用方法: 直接发送文字问题,免费额度有限，请珍惜使用.
		按文字生成图片的功能正在开发中
		`
		sendMessageInfo.ParseMode = "HTML"
		telegramService.SendMessage(sendMessageInfo)
	}

}
